### ISSUE TITLE
Add graphs and statistics dashboard for card review analytics

### ISSUE THREAD

**Issue by Kure-ru** [Kure-ru/Kioku#31]
### What type of graphs?
- Study days heatmap
- Card count over time (bar chart)
- Button press (easy, good, hard or again)
- New cards added / day

### Tasks
- [ ] Create API endpoints for study dates, button press stats and new cards addition
- [ ] Fetch and display data for each graph using the new API endpoints.
- [ ] Create a Stats page to display all visualizations
- [ ] Create tests
